spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flm_project
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/demo
          jwk-set-uri: http://localhost:8081/realms/demo/protocol/openid-connect/certs

server:
  port: 8085

# CORS CONFIG
cors:
  allowed-origins:
    - http://localhost:8010 # Frontend
    - http://localhost:8090 # Profile service
    - http://localhost:8020 # Admin service