server:
  port: 8086

spring:
  application:
    name: migration
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/flm_project
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
